// <auto-generated />
using System;
using Bookingweb.Enums;
using Bookingweb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookingweb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509062333_AddAvatarAndAddressToDoctor")]
    partial class AddAvatarAndAddressToDoctor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "appointment_status", new[] { "PENDING", "CONFIRMED", "COMPLETED", "CANCELLED", "SCHEDULED", "PATIENT_CONFIRMED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "USER", "DOCTOR", "ADMIN" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookingweb.Models.appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<AppointmentStatus>("Status")
                        .HasColumnType("appointment_status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("doctor_id")
                        .HasColumnType("uuid");

                    b.Property<string>("note")
                        .HasColumnType("text");

                    b.Property<Guid>("schedule_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id")
                        .HasName("appointments_pkey");

                    b.HasIndex("schedule_id");

                    b.HasIndex(new[] { "doctor_id" }, "idx_appointment_doctor");

                    b.HasIndex(new[] { "user_id" }, "idx_appointment_user");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("Bookingweb.Models.doctor", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int?>("experience_years")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("specialty_id")
                        .HasColumnType("integer");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id")
                        .HasName("doctors_pkey");

                    b.HasIndex("specialty_id");

                    b.HasIndex(new[] { "user_id" }, "doctors_user_id_key")
                        .IsUnique();

                    b.ToTable("doctors");
                });

            modelBuilder.Entity("Bookingweb.Models.schedule", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("doctor_id")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("end_time")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("start_time")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("work_date")
                        .HasColumnType("date");

                    b.HasKey("id")
                        .HasName("schedules_pkey");

                    b.HasIndex(new[] { "doctor_id" }, "idx_schedule_doctor");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("Bookingweb.Models.specialty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id")
                        .HasName("specialties_pkey");

                    b.HasIndex(new[] { "name" }, "specialties_name_key")
                        .IsUnique();

                    b.ToTable("specialties");
                });

            modelBuilder.Entity("Bookingweb.Models.user", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "email" }, "idx_users_email");

                    b.HasIndex(new[] { "email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Bookingweb.Models.appointment", b =>
                {
                    b.HasOne("Bookingweb.Models.doctor", "doctor")
                        .WithMany("appointments")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_doctor");

                    b.HasOne("Bookingweb.Models.schedule", "schedule")
                        .WithMany("appointments")
                        .HasForeignKey("schedule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_schedule");

                    b.HasOne("Bookingweb.Models.user", "user")
                        .WithMany("appointments")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_user");

                    b.Navigation("doctor");

                    b.Navigation("schedule");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Bookingweb.Models.doctor", b =>
                {
                    b.HasOne("Bookingweb.Models.specialty", "specialty")
                        .WithMany("doctors")
                        .HasForeignKey("specialty_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_doctor_specialty");

                    b.HasOne("Bookingweb.Models.user", "user")
                        .WithOne("doctor")
                        .HasForeignKey("Bookingweb.Models.doctor", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctor_user");

                    b.Navigation("specialty");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Bookingweb.Models.schedule", b =>
                {
                    b.HasOne("Bookingweb.Models.doctor", "doctor")
                        .WithMany("schedules")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_doctor");

                    b.Navigation("doctor");
                });

            modelBuilder.Entity("Bookingweb.Models.doctor", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("schedules");
                });

            modelBuilder.Entity("Bookingweb.Models.schedule", b =>
                {
                    b.Navigation("appointments");
                });

            modelBuilder.Entity("Bookingweb.Models.specialty", b =>
                {
                    b.Navigation("doctors");
                });

            modelBuilder.Entity("Bookingweb.Models.user", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
